<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Carne bovina assada',
            'Carne de panela',
            'Churrasco',
            'Hambúrgueres artesanais',
            'Carne de porco',
            'Frango assado',
            'Frango grelhado',
            'Frango empanado',
            'Peru de festa',
            'Coxinha da asa',
            'Peixes grelhados',
            'Moqueca de peixe',
            'Bacalhau',
            'Camarões',
            'Polvo e lula',
            'Lasanha',
            'Espaguete',
            'Ravioli',
            'Nhoque',
            'Talharim',
            'Saladas verdes',
            'Salada de batata',
            'Vinagrete',
            'Farofa',
            'Purê de batata',
            'Pão caseiro',
            'Pão de queijo',
            'Focaccia',
            'Croissant',
            'Pizza',
            'Sopa de legumes',
            'Caldo verde',
            'Creme de mandioquinha',
            'Canja de galinha',
            'Caldo de feijão',
            'Feijoada',
            'Vatapá',
            'Moqueca baiana',
            'Acarajé',
            'Baião de dois',
            'Bolos',
            'Pudins',
            'Mousse',
            'Pavê',
            'Cheesecake',
            'Brigadeiro',
            'Beijinho',
            'Cocada',
            'Quindim',
            'Brownie',
            'Risotos',
            'Cuscuz nordestino',
            'Escondidinho',
            'Estrogonofe',
            'Tacos mexicanos',
            'Burritos',
            'Nachos',
            'Guacamole',
            'Sushi',
            'Temaki',
            'Yakissoba',
            'Ramen',
            'Gyoza',
            'Curry indiano',
            'Chutney',
            'Tikka Masala',
            'Falafel',
            'Kibe',
            'Tabule',
            'Homus',
            'Shawarma',
            'Couscous marroquino',
            'Paella espanhola',
            'Tapas',
            'Tortilla espanhola',
            'Croquetes',
            'Quiche',
            'Ratatouille',
            'Cassoulet',
            'Bouillabaisse',
            'Fondue',
            'Schnitzel',
            'Pretzel',
            'Sauerkraut',
            'Goulash',
            'Pierogi',
            'Borscht',
            'Chutney de manga',
            'Polenta',
            'Arancini',
            'Frittata',
            'Panquecas americanas',
            'Crepes',
            'Waffles',
            'Donuts',
            'Churros',
            'Tiramisu',
            'Panetone',
            'Rabanada',
            'Gelato italiano',
        ];

        foreach ($categories as $name) {
            Category::firstOrCreate(['name' => $name]);
        }
    }
}
